python src/main.py \
    --generate-pddl \
    --pddl-type propositional \
    --world-config task-worlds/worlds/Place_Wood/Place_Wood_Easy.yaml \
    --domain-name test_domain \
    --problem-name test_problem \
    --domain-file problems/tasks/Build_Cross/Easy/propositional/d.pddl \
    --problem-file problems/tasks/Build_Cross/Easy/propositional/p.pddl \
    --max-inventory-stack 5 \
    --observation-range "(5, 4, 3)" \
    --agent-start-position "(0, 5, 0)" 