0.0: (drop-diamond steve diamond0 )
1.0: (move-south steve )
2.0: (move-east steve )
3.0: (move-south steve )
4.0: (move-east steve )
5.0: (move-south steve )
6.0: (move-east steve )
7.0: (move-east steve )
8.0: (move-south steve )
9.0: (move-east steve )
10.0: (move-south steve )
11.0: (pickup-oak-log steve oak-log0 )