(define (problem first_world_problem)
	(:domain first_world)
(:objects
	steve - agent
	dirt-block0 dirt-block1 dirt-block2 dirt-block3 dirt-block4 dirt-block5 dirt-block6 dirt-block7 dirt-block8 dirt-block9 dirt-block10 dirt-block11 dirt-block12 dirt-block13 dirt-block14 dirt-block15 dirt-block16 dirt-block17 dirt-block18 dirt-block19 dirt-block20 dirt-block21 dirt-block22 dirt-block23 dirt-block24 dirt-block25 dirt-block26 dirt-block27 dirt-block28 dirt-block29 dirt-block30 dirt-block31 dirt-block32 dirt-block33 dirt-block34 dirt-block35 dirt-block36 dirt-block37 dirt-block38 dirt-block39 dirt-block40 dirt-block41 dirt-block42 dirt-block43 dirt-block44 dirt-block45 dirt-block46 dirt-block47 dirt-block48 dirt-block49 dirt-block50 dirt-block51 dirt-block52 dirt-block53 dirt-block54 dirt-block55 dirt-block56 dirt-block57 dirt-block58 dirt-block59 dirt-block60 dirt-block61 dirt-block62 dirt-block63 dirt-block64 dirt-block65 dirt-block66 dirt-block67 dirt-block68 dirt-block69 dirt-block70 dirt-block71 dirt-block72 dirt-block73 dirt-block74 dirt-block75 dirt-block76 dirt-block77 dirt-block78 dirt-block79 dirt-block80 - dirt-block
	grass_block-block0 grass_block-block1 grass_block-block2 grass_block-block3 grass_block-block4 grass_block-block5 grass_block-block6 grass_block-block7 grass_block-block8 grass_block-block9 grass_block-block10 grass_block-block11 grass_block-block12 grass_block-block13 grass_block-block14 grass_block-block15 grass_block-block16 grass_block-block17 grass_block-block18 grass_block-block19 grass_block-block20 grass_block-block21 grass_block-block22 grass_block-block23 grass_block-block24 grass_block-block25 grass_block-block26 grass_block-block27 grass_block-block28 grass_block-block29 grass_block-block30 grass_block-block31 grass_block-block32 grass_block-block33 grass_block-block34 grass_block-block35 grass_block-block36 grass_block-block37 grass_block-block38 grass_block-block39 grass_block-block40 grass_block-block41 grass_block-block42 grass_block-block43 grass_block-block44 grass_block-block45 grass_block-block46 grass_block-block47 grass_block-block48 grass_block-block49 grass_block-block50 grass_block-block51 grass_block-block52 grass_block-block53 grass_block-block54 grass_block-block55 grass_block-block56 grass_block-block57 grass_block-block58 grass_block-block59 grass_block-block60 grass_block-block61 grass_block-block62 grass_block-block63 grass_block-block64 grass_block-block65 grass_block-block66 grass_block-block67 grass_block-block68 grass_block-block69 grass_block-block70 grass_block-block71 grass_block-block72 grass_block-block73 grass_block-block74 grass_block-block75 grass_block-block76 grass_block-block77 grass_block-block78 grass_block-block79 grass_block-block80 - grass_block-block
	obsidian-block0 - obsidian-block
	log-block0 - log-block
	diamond0 - diamond
	log0 - log
)
(:init
	(agent-alive steve)
	(not (goal-achieved steve))
	(= (x steve) 0)
	(= (y steve) 4)
	(= (z steve) 0)
	(= (agent-num-diamond steve) 0)
	(= (agent-num-log steve) 64)
	(block-present dirt-block0)
	(= (x dirt-block0) -3)
	(= (y dirt-block0) 2)
	(= (z dirt-block0) -3)
	(= (block-hits dirt-block0) 0)
	(block-present dirt-block1)
	(= (x dirt-block1) -3)
	(= (y dirt-block1) 2)
	(= (z dirt-block1) -2)
	(= (block-hits dirt-block1) 0)
	(block-present dirt-block2)
	(= (x dirt-block2) -3)
	(= (y dirt-block2) 2)
	(= (z dirt-block2) -1)
	(= (block-hits dirt-block2) 0)
	(block-present dirt-block3)
	(= (x dirt-block3) -3)
	(= (y dirt-block3) 2)
	(= (z dirt-block3) 0)
	(= (block-hits dirt-block3) 0)
	(block-present dirt-block4)
	(= (x dirt-block4) -3)
	(= (y dirt-block4) 2)
	(= (z dirt-block4) 0)
	(= (block-hits dirt-block4) 0)
	(block-present dirt-block5)
	(= (x dirt-block5) -3)
	(= (y dirt-block5) 2)
	(= (z dirt-block5) 1)
	(= (block-hits dirt-block5) 0)
	(block-present dirt-block6)
	(= (x dirt-block6) -3)
	(= (y dirt-block6) 2)
	(= (z dirt-block6) 2)
	(= (block-hits dirt-block6) 0)
	(block-present dirt-block7)
	(= (x dirt-block7) -3)
	(= (y dirt-block7) 2)
	(= (z dirt-block7) 3)
	(= (block-hits dirt-block7) 0)
	(block-present dirt-block8)
	(= (x dirt-block8) -3)
	(= (y dirt-block8) 2)
	(= (z dirt-block8) 4)
	(= (block-hits dirt-block8) 0)
	(block-present dirt-block9)
	(= (x dirt-block9) -2)
	(= (y dirt-block9) 2)
	(= (z dirt-block9) -3)
	(= (block-hits dirt-block9) 0)
	(block-present dirt-block10)
	(= (x dirt-block10) -2)
	(= (y dirt-block10) 2)
	(= (z dirt-block10) -2)
	(= (block-hits dirt-block10) 0)
	(block-present dirt-block11)
	(= (x dirt-block11) -2)
	(= (y dirt-block11) 2)
	(= (z dirt-block11) -1)
	(= (block-hits dirt-block11) 0)
	(block-present dirt-block12)
	(= (x dirt-block12) -2)
	(= (y dirt-block12) 2)
	(= (z dirt-block12) 0)
	(= (block-hits dirt-block12) 0)
	(block-present dirt-block13)
	(= (x dirt-block13) -2)
	(= (y dirt-block13) 2)
	(= (z dirt-block13) 0)
	(= (block-hits dirt-block13) 0)
	(block-present dirt-block14)
	(= (x dirt-block14) -2)
	(= (y dirt-block14) 2)
	(= (z dirt-block14) 1)
	(= (block-hits dirt-block14) 0)
	(block-present dirt-block15)
	(= (x dirt-block15) -2)
	(= (y dirt-block15) 2)
	(= (z dirt-block15) 2)
	(= (block-hits dirt-block15) 0)
	(block-present dirt-block16)
	(= (x dirt-block16) -2)
	(= (y dirt-block16) 2)
	(= (z dirt-block16) 3)
	(= (block-hits dirt-block16) 0)
	(block-present dirt-block17)
	(= (x dirt-block17) -2)
	(= (y dirt-block17) 2)
	(= (z dirt-block17) 4)
	(= (block-hits dirt-block17) 0)
	(block-present dirt-block18)
	(= (x dirt-block18) -1)
	(= (y dirt-block18) 2)
	(= (z dirt-block18) -3)
	(= (block-hits dirt-block18) 0)
	(block-present dirt-block19)
	(= (x dirt-block19) -1)
	(= (y dirt-block19) 2)
	(= (z dirt-block19) -2)
	(= (block-hits dirt-block19) 0)
	(block-present dirt-block20)
	(= (x dirt-block20) -1)
	(= (y dirt-block20) 2)
	(= (z dirt-block20) -1)
	(= (block-hits dirt-block20) 0)
	(block-present dirt-block21)
	(= (x dirt-block21) -1)
	(= (y dirt-block21) 2)
	(= (z dirt-block21) 0)
	(= (block-hits dirt-block21) 0)
	(block-present dirt-block22)
	(= (x dirt-block22) -1)
	(= (y dirt-block22) 2)
	(= (z dirt-block22) 0)
	(= (block-hits dirt-block22) 0)
	(block-present dirt-block23)
	(= (x dirt-block23) -1)
	(= (y dirt-block23) 2)
	(= (z dirt-block23) 1)
	(= (block-hits dirt-block23) 0)
	(block-present dirt-block24)
	(= (x dirt-block24) -1)
	(= (y dirt-block24) 2)
	(= (z dirt-block24) 2)
	(= (block-hits dirt-block24) 0)
	(block-present dirt-block25)
	(= (x dirt-block25) -1)
	(= (y dirt-block25) 2)
	(= (z dirt-block25) 3)
	(= (block-hits dirt-block25) 0)
	(block-present dirt-block26)
	(= (x dirt-block26) -1)
	(= (y dirt-block26) 2)
	(= (z dirt-block26) 4)
	(= (block-hits dirt-block26) 0)
	(block-present dirt-block27)
	(= (x dirt-block27) 0)
	(= (y dirt-block27) 2)
	(= (z dirt-block27) -3)
	(= (block-hits dirt-block27) 0)
	(block-present dirt-block28)
	(= (x dirt-block28) 0)
	(= (y dirt-block28) 2)
	(= (z dirt-block28) -2)
	(= (block-hits dirt-block28) 0)
	(block-present dirt-block29)
	(= (x dirt-block29) 0)
	(= (y dirt-block29) 2)
	(= (z dirt-block29) -1)
	(= (block-hits dirt-block29) 0)
	(block-present dirt-block30)
	(= (x dirt-block30) 0)
	(= (y dirt-block30) 2)
	(= (z dirt-block30) 0)
	(= (block-hits dirt-block30) 0)
	(block-present dirt-block31)
	(= (x dirt-block31) 0)
	(= (y dirt-block31) 2)
	(= (z dirt-block31) 0)
	(= (block-hits dirt-block31) 0)
	(block-present dirt-block32)
	(= (x dirt-block32) 0)
	(= (y dirt-block32) 2)
	(= (z dirt-block32) 1)
	(= (block-hits dirt-block32) 0)
	(block-present dirt-block33)
	(= (x dirt-block33) 0)
	(= (y dirt-block33) 2)
	(= (z dirt-block33) 2)
	(= (block-hits dirt-block33) 0)
	(block-present dirt-block34)
	(= (x dirt-block34) 0)
	(= (y dirt-block34) 2)
	(= (z dirt-block34) 3)
	(= (block-hits dirt-block34) 0)
	(block-present dirt-block35)
	(= (x dirt-block35) 0)
	(= (y dirt-block35) 2)
	(= (z dirt-block35) 4)
	(= (block-hits dirt-block35) 0)
	(block-present dirt-block36)
	(= (x dirt-block36) 0)
	(= (y dirt-block36) 2)
	(= (z dirt-block36) -3)
	(= (block-hits dirt-block36) 0)
	(block-present dirt-block37)
	(= (x dirt-block37) 0)
	(= (y dirt-block37) 2)
	(= (z dirt-block37) -2)
	(= (block-hits dirt-block37) 0)
	(block-present dirt-block38)
	(= (x dirt-block38) 0)
	(= (y dirt-block38) 2)
	(= (z dirt-block38) -1)
	(= (block-hits dirt-block38) 0)
	(block-present dirt-block39)
	(= (x dirt-block39) 0)
	(= (y dirt-block39) 2)
	(= (z dirt-block39) 0)
	(= (block-hits dirt-block39) 0)
	(block-present dirt-block40)
	(= (x dirt-block40) 0)
	(= (y dirt-block40) 2)
	(= (z dirt-block40) 0)
	(= (block-hits dirt-block40) 0)
	(block-present dirt-block41)
	(= (x dirt-block41) 0)
	(= (y dirt-block41) 2)
	(= (z dirt-block41) 1)
	(= (block-hits dirt-block41) 0)
	(block-present dirt-block42)
	(= (x dirt-block42) 0)
	(= (y dirt-block42) 2)
	(= (z dirt-block42) 2)
	(= (block-hits dirt-block42) 0)
	(block-present dirt-block43)
	(= (x dirt-block43) 0)
	(= (y dirt-block43) 2)
	(= (z dirt-block43) 3)
	(= (block-hits dirt-block43) 0)
	(block-present dirt-block44)
	(= (x dirt-block44) 0)
	(= (y dirt-block44) 2)
	(= (z dirt-block44) 4)
	(= (block-hits dirt-block44) 0)
	(block-present dirt-block45)
	(= (x dirt-block45) 1)
	(= (y dirt-block45) 2)
	(= (z dirt-block45) -3)
	(= (block-hits dirt-block45) 0)
	(block-present dirt-block46)
	(= (x dirt-block46) 1)
	(= (y dirt-block46) 2)
	(= (z dirt-block46) -2)
	(= (block-hits dirt-block46) 0)
	(block-present dirt-block47)
	(= (x dirt-block47) 1)
	(= (y dirt-block47) 2)
	(= (z dirt-block47) -1)
	(= (block-hits dirt-block47) 0)
	(block-present dirt-block48)
	(= (x dirt-block48) 1)
	(= (y dirt-block48) 2)
	(= (z dirt-block48) 0)
	(= (block-hits dirt-block48) 0)
	(block-present dirt-block49)
	(= (x dirt-block49) 1)
	(= (y dirt-block49) 2)
	(= (z dirt-block49) 0)
	(= (block-hits dirt-block49) 0)
	(block-present dirt-block50)
	(= (x dirt-block50) 1)
	(= (y dirt-block50) 2)
	(= (z dirt-block50) 1)
	(= (block-hits dirt-block50) 0)
	(block-present dirt-block51)
	(= (x dirt-block51) 1)
	(= (y dirt-block51) 2)
	(= (z dirt-block51) 2)
	(= (block-hits dirt-block51) 0)
	(block-present dirt-block52)
	(= (x dirt-block52) 1)
	(= (y dirt-block52) 2)
	(= (z dirt-block52) 3)
	(= (block-hits dirt-block52) 0)
	(block-present dirt-block53)
	(= (x dirt-block53) 1)
	(= (y dirt-block53) 2)
	(= (z dirt-block53) 4)
	(= (block-hits dirt-block53) 0)
	(block-present dirt-block54)
	(= (x dirt-block54) 2)
	(= (y dirt-block54) 2)
	(= (z dirt-block54) -3)
	(= (block-hits dirt-block54) 0)
	(block-present dirt-block55)
	(= (x dirt-block55) 2)
	(= (y dirt-block55) 2)
	(= (z dirt-block55) -2)
	(= (block-hits dirt-block55) 0)
	(block-present dirt-block56)
	(= (x dirt-block56) 2)
	(= (y dirt-block56) 2)
	(= (z dirt-block56) -1)
	(= (block-hits dirt-block56) 0)
	(block-present dirt-block57)
	(= (x dirt-block57) 2)
	(= (y dirt-block57) 2)
	(= (z dirt-block57) 0)
	(= (block-hits dirt-block57) 0)
	(block-present dirt-block58)
	(= (x dirt-block58) 2)
	(= (y dirt-block58) 2)
	(= (z dirt-block58) 0)
	(= (block-hits dirt-block58) 0)
	(block-present dirt-block59)
	(= (x dirt-block59) 2)
	(= (y dirt-block59) 2)
	(= (z dirt-block59) 1)
	(= (block-hits dirt-block59) 0)
	(block-present dirt-block60)
	(= (x dirt-block60) 2)
	(= (y dirt-block60) 2)
	(= (z dirt-block60) 2)
	(= (block-hits dirt-block60) 0)
	(block-present dirt-block61)
	(= (x dirt-block61) 2)
	(= (y dirt-block61) 2)
	(= (z dirt-block61) 3)
	(= (block-hits dirt-block61) 0)
	(block-present dirt-block62)
	(= (x dirt-block62) 2)
	(= (y dirt-block62) 2)
	(= (z dirt-block62) 4)
	(= (block-hits dirt-block62) 0)
	(block-present dirt-block63)
	(= (x dirt-block63) 3)
	(= (y dirt-block63) 2)
	(= (z dirt-block63) -3)
	(= (block-hits dirt-block63) 0)
	(block-present dirt-block64)
	(= (x dirt-block64) 3)
	(= (y dirt-block64) 2)
	(= (z dirt-block64) -2)
	(= (block-hits dirt-block64) 0)
	(block-present dirt-block65)
	(= (x dirt-block65) 3)
	(= (y dirt-block65) 2)
	(= (z dirt-block65) -1)
	(= (block-hits dirt-block65) 0)
	(block-present dirt-block66)
	(= (x dirt-block66) 3)
	(= (y dirt-block66) 2)
	(= (z dirt-block66) 0)
	(= (block-hits dirt-block66) 0)
	(block-present dirt-block67)
	(= (x dirt-block67) 3)
	(= (y dirt-block67) 2)
	(= (z dirt-block67) 0)
	(= (block-hits dirt-block67) 0)
	(block-present dirt-block68)
	(= (x dirt-block68) 3)
	(= (y dirt-block68) 2)
	(= (z dirt-block68) 1)
	(= (block-hits dirt-block68) 0)
	(block-present dirt-block69)
	(= (x dirt-block69) 3)
	(= (y dirt-block69) 2)
	(= (z dirt-block69) 2)
	(= (block-hits dirt-block69) 0)
	(block-present dirt-block70)
	(= (x dirt-block70) 3)
	(= (y dirt-block70) 2)
	(= (z dirt-block70) 3)
	(= (block-hits dirt-block70) 0)
	(block-present dirt-block71)
	(= (x dirt-block71) 3)
	(= (y dirt-block71) 2)
	(= (z dirt-block71) 4)
	(= (block-hits dirt-block71) 0)
	(block-present dirt-block72)
	(= (x dirt-block72) 4)
	(= (y dirt-block72) 2)
	(= (z dirt-block72) -3)
	(= (block-hits dirt-block72) 0)
	(block-present dirt-block73)
	(= (x dirt-block73) 4)
	(= (y dirt-block73) 2)
	(= (z dirt-block73) -2)
	(= (block-hits dirt-block73) 0)
	(block-present dirt-block74)
	(= (x dirt-block74) 4)
	(= (y dirt-block74) 2)
	(= (z dirt-block74) -1)
	(= (block-hits dirt-block74) 0)
	(block-present dirt-block75)
	(= (x dirt-block75) 4)
	(= (y dirt-block75) 2)
	(= (z dirt-block75) 0)
	(= (block-hits dirt-block75) 0)
	(block-present dirt-block76)
	(= (x dirt-block76) 4)
	(= (y dirt-block76) 2)
	(= (z dirt-block76) 0)
	(= (block-hits dirt-block76) 0)
	(block-present dirt-block77)
	(= (x dirt-block77) 4)
	(= (y dirt-block77) 2)
	(= (z dirt-block77) 1)
	(= (block-hits dirt-block77) 0)
	(block-present dirt-block78)
	(= (x dirt-block78) 4)
	(= (y dirt-block78) 2)
	(= (z dirt-block78) 2)
	(= (block-hits dirt-block78) 0)
	(block-present dirt-block79)
	(= (x dirt-block79) 4)
	(= (y dirt-block79) 2)
	(= (z dirt-block79) 3)
	(= (block-hits dirt-block79) 0)
	(block-present dirt-block80)
	(= (x dirt-block80) 4)
	(= (y dirt-block80) 2)
	(= (z dirt-block80) 4)
	(= (block-hits dirt-block80) 0)
	(block-present grass_block-block0)
	(= (x grass_block-block0) -3)
	(= (y grass_block-block0) 3)
	(= (z grass_block-block0) -3)
	(= (block-hits grass_block-block0) 0)
	(block-present grass_block-block1)
	(= (x grass_block-block1) -3)
	(= (y grass_block-block1) 3)
	(= (z grass_block-block1) -2)
	(= (block-hits grass_block-block1) 0)
	(block-present grass_block-block2)
	(= (x grass_block-block2) -3)
	(= (y grass_block-block2) 3)
	(= (z grass_block-block2) -1)
	(= (block-hits grass_block-block2) 0)
	(block-present grass_block-block3)
	(= (x grass_block-block3) -3)
	(= (y grass_block-block3) 3)
	(= (z grass_block-block3) 0)
	(= (block-hits grass_block-block3) 0)
	(block-present grass_block-block4)
	(= (x grass_block-block4) -3)
	(= (y grass_block-block4) 3)
	(= (z grass_block-block4) 0)
	(= (block-hits grass_block-block4) 0)
	(block-present grass_block-block5)
	(= (x grass_block-block5) -3)
	(= (y grass_block-block5) 3)
	(= (z grass_block-block5) 1)
	(= (block-hits grass_block-block5) 0)
	(block-present grass_block-block6)
	(= (x grass_block-block6) -3)
	(= (y grass_block-block6) 3)
	(= (z grass_block-block6) 2)
	(= (block-hits grass_block-block6) 0)
	(block-present grass_block-block7)
	(= (x grass_block-block7) -3)
	(= (y grass_block-block7) 3)
	(= (z grass_block-block7) 3)
	(= (block-hits grass_block-block7) 0)
	(block-present grass_block-block8)
	(= (x grass_block-block8) -3)
	(= (y grass_block-block8) 3)
	(= (z grass_block-block8) 4)
	(= (block-hits grass_block-block8) 0)
	(block-present grass_block-block9)
	(= (x grass_block-block9) -2)
	(= (y grass_block-block9) 3)
	(= (z grass_block-block9) -3)
	(= (block-hits grass_block-block9) 0)
	(block-present grass_block-block10)
	(= (x grass_block-block10) -2)
	(= (y grass_block-block10) 3)
	(= (z grass_block-block10) -2)
	(= (block-hits grass_block-block10) 0)
	(block-present grass_block-block11)
	(= (x grass_block-block11) -2)
	(= (y grass_block-block11) 3)
	(= (z grass_block-block11) -1)
	(= (block-hits grass_block-block11) 0)
	(block-present grass_block-block12)
	(= (x grass_block-block12) -2)
	(= (y grass_block-block12) 3)
	(= (z grass_block-block12) 0)
	(= (block-hits grass_block-block12) 0)
	(block-present grass_block-block13)
	(= (x grass_block-block13) -2)
	(= (y grass_block-block13) 3)
	(= (z grass_block-block13) 0)
	(= (block-hits grass_block-block13) 0)
	(block-present grass_block-block14)
	(= (x grass_block-block14) -2)
	(= (y grass_block-block14) 3)
	(= (z grass_block-block14) 1)
	(= (block-hits grass_block-block14) 0)
	(block-present grass_block-block15)
	(= (x grass_block-block15) -2)
	(= (y grass_block-block15) 3)
	(= (z grass_block-block15) 2)
	(= (block-hits grass_block-block15) 0)
	(block-present grass_block-block16)
	(= (x grass_block-block16) -2)
	(= (y grass_block-block16) 3)
	(= (z grass_block-block16) 3)
	(= (block-hits grass_block-block16) 0)
	(block-present grass_block-block17)
	(= (x grass_block-block17) -2)
	(= (y grass_block-block17) 3)
	(= (z grass_block-block17) 4)
	(= (block-hits grass_block-block17) 0)
	(block-present grass_block-block18)
	(= (x grass_block-block18) -1)
	(= (y grass_block-block18) 3)
	(= (z grass_block-block18) -3)
	(= (block-hits grass_block-block18) 0)
	(block-present grass_block-block19)
	(= (x grass_block-block19) -1)
	(= (y grass_block-block19) 3)
	(= (z grass_block-block19) -2)
	(= (block-hits grass_block-block19) 0)
	(block-present grass_block-block20)
	(= (x grass_block-block20) -1)
	(= (y grass_block-block20) 3)
	(= (z grass_block-block20) -1)
	(= (block-hits grass_block-block20) 0)
	(block-present grass_block-block21)
	(= (x grass_block-block21) -1)
	(= (y grass_block-block21) 3)
	(= (z grass_block-block21) 0)
	(= (block-hits grass_block-block21) 0)
	(block-present grass_block-block22)
	(= (x grass_block-block22) -1)
	(= (y grass_block-block22) 3)
	(= (z grass_block-block22) 0)
	(= (block-hits grass_block-block22) 0)
	(block-present grass_block-block23)
	(= (x grass_block-block23) -1)
	(= (y grass_block-block23) 3)
	(= (z grass_block-block23) 1)
	(= (block-hits grass_block-block23) 0)
	(block-present grass_block-block24)
	(= (x grass_block-block24) -1)
	(= (y grass_block-block24) 3)
	(= (z grass_block-block24) 2)
	(= (block-hits grass_block-block24) 0)
	(block-present grass_block-block25)
	(= (x grass_block-block25) -1)
	(= (y grass_block-block25) 3)
	(= (z grass_block-block25) 3)
	(= (block-hits grass_block-block25) 0)
	(block-present grass_block-block26)
	(= (x grass_block-block26) -1)
	(= (y grass_block-block26) 3)
	(= (z grass_block-block26) 4)
	(= (block-hits grass_block-block26) 0)
	(block-present grass_block-block27)
	(= (x grass_block-block27) 0)
	(= (y grass_block-block27) 3)
	(= (z grass_block-block27) -3)
	(= (block-hits grass_block-block27) 0)
	(block-present grass_block-block28)
	(= (x grass_block-block28) 0)
	(= (y grass_block-block28) 3)
	(= (z grass_block-block28) -2)
	(= (block-hits grass_block-block28) 0)
	(block-present grass_block-block29)
	(= (x grass_block-block29) 0)
	(= (y grass_block-block29) 3)
	(= (z grass_block-block29) -1)
	(= (block-hits grass_block-block29) 0)
	(block-present grass_block-block30)
	(= (x grass_block-block30) 0)
	(= (y grass_block-block30) 3)
	(= (z grass_block-block30) 0)
	(= (block-hits grass_block-block30) 0)
	(block-present grass_block-block31)
	(= (x grass_block-block31) 0)
	(= (y grass_block-block31) 3)
	(= (z grass_block-block31) 0)
	(= (block-hits grass_block-block31) 0)
	(block-present grass_block-block32)
	(= (x grass_block-block32) 0)
	(= (y grass_block-block32) 3)
	(= (z grass_block-block32) 1)
	(= (block-hits grass_block-block32) 0)
	(block-present grass_block-block33)
	(= (x grass_block-block33) 0)
	(= (y grass_block-block33) 3)
	(= (z grass_block-block33) 2)
	(= (block-hits grass_block-block33) 0)
	(block-present grass_block-block34)
	(= (x grass_block-block34) 0)
	(= (y grass_block-block34) 3)
	(= (z grass_block-block34) 3)
	(= (block-hits grass_block-block34) 0)
	(block-present grass_block-block35)
	(= (x grass_block-block35) 0)
	(= (y grass_block-block35) 3)
	(= (z grass_block-block35) 4)
	(= (block-hits grass_block-block35) 0)
	(block-present grass_block-block36)
	(= (x grass_block-block36) 0)
	(= (y grass_block-block36) 3)
	(= (z grass_block-block36) -3)
	(= (block-hits grass_block-block36) 0)
	(block-present grass_block-block37)
	(= (x grass_block-block37) 0)
	(= (y grass_block-block37) 3)
	(= (z grass_block-block37) -2)
	(= (block-hits grass_block-block37) 0)
	(block-present grass_block-block38)
	(= (x grass_block-block38) 0)
	(= (y grass_block-block38) 3)
	(= (z grass_block-block38) -1)
	(= (block-hits grass_block-block38) 0)
	(block-present grass_block-block39)
	(= (x grass_block-block39) 0)
	(= (y grass_block-block39) 3)
	(= (z grass_block-block39) 0)
	(= (block-hits grass_block-block39) 0)
	(block-present grass_block-block40)
	(= (x grass_block-block40) 0)
	(= (y grass_block-block40) 3)
	(= (z grass_block-block40) 0)
	(= (block-hits grass_block-block40) 0)
	(block-present grass_block-block41)
	(= (x grass_block-block41) 0)
	(= (y grass_block-block41) 3)
	(= (z grass_block-block41) 1)
	(= (block-hits grass_block-block41) 0)
	(block-present grass_block-block42)
	(= (x grass_block-block42) 0)
	(= (y grass_block-block42) 3)
	(= (z grass_block-block42) 2)
	(= (block-hits grass_block-block42) 0)
	(block-present grass_block-block43)
	(= (x grass_block-block43) 0)
	(= (y grass_block-block43) 3)
	(= (z grass_block-block43) 3)
	(= (block-hits grass_block-block43) 0)
	(block-present grass_block-block44)
	(= (x grass_block-block44) 0)
	(= (y grass_block-block44) 3)
	(= (z grass_block-block44) 4)
	(= (block-hits grass_block-block44) 0)
	(block-present grass_block-block45)
	(= (x grass_block-block45) 1)
	(= (y grass_block-block45) 3)
	(= (z grass_block-block45) -3)
	(= (block-hits grass_block-block45) 0)
	(block-present grass_block-block46)
	(= (x grass_block-block46) 1)
	(= (y grass_block-block46) 3)
	(= (z grass_block-block46) -2)
	(= (block-hits grass_block-block46) 0)
	(block-present grass_block-block47)
	(= (x grass_block-block47) 1)
	(= (y grass_block-block47) 3)
	(= (z grass_block-block47) -1)
	(= (block-hits grass_block-block47) 0)
	(block-present grass_block-block48)
	(= (x grass_block-block48) 1)
	(= (y grass_block-block48) 3)
	(= (z grass_block-block48) 0)
	(= (block-hits grass_block-block48) 0)
	(block-present grass_block-block49)
	(= (x grass_block-block49) 1)
	(= (y grass_block-block49) 3)
	(= (z grass_block-block49) 0)
	(= (block-hits grass_block-block49) 0)
	(block-present grass_block-block50)
	(= (x grass_block-block50) 1)
	(= (y grass_block-block50) 3)
	(= (z grass_block-block50) 1)
	(= (block-hits grass_block-block50) 0)
	(block-present grass_block-block51)
	(= (x grass_block-block51) 1)
	(= (y grass_block-block51) 3)
	(= (z grass_block-block51) 2)
	(= (block-hits grass_block-block51) 0)
	(block-present grass_block-block52)
	(= (x grass_block-block52) 1)
	(= (y grass_block-block52) 3)
	(= (z grass_block-block52) 3)
	(= (block-hits grass_block-block52) 0)
	(block-present grass_block-block53)
	(= (x grass_block-block53) 1)
	(= (y grass_block-block53) 3)
	(= (z grass_block-block53) 4)
	(= (block-hits grass_block-block53) 0)
	(block-present grass_block-block54)
	(= (x grass_block-block54) 2)
	(= (y grass_block-block54) 3)
	(= (z grass_block-block54) -3)
	(= (block-hits grass_block-block54) 0)
	(block-present grass_block-block55)
	(= (x grass_block-block55) 2)
	(= (y grass_block-block55) 3)
	(= (z grass_block-block55) -2)
	(= (block-hits grass_block-block55) 0)
	(block-present grass_block-block56)
	(= (x grass_block-block56) 2)
	(= (y grass_block-block56) 3)
	(= (z grass_block-block56) -1)
	(= (block-hits grass_block-block56) 0)
	(block-present grass_block-block57)
	(= (x grass_block-block57) 2)
	(= (y grass_block-block57) 3)
	(= (z grass_block-block57) 0)
	(= (block-hits grass_block-block57) 0)
	(block-present grass_block-block58)
	(= (x grass_block-block58) 2)
	(= (y grass_block-block58) 3)
	(= (z grass_block-block58) 0)
	(= (block-hits grass_block-block58) 0)
	(block-present grass_block-block59)
	(= (x grass_block-block59) 2)
	(= (y grass_block-block59) 3)
	(= (z grass_block-block59) 1)
	(= (block-hits grass_block-block59) 0)
	(block-present grass_block-block60)
	(= (x grass_block-block60) 2)
	(= (y grass_block-block60) 3)
	(= (z grass_block-block60) 2)
	(= (block-hits grass_block-block60) 0)
	(block-present grass_block-block61)
	(= (x grass_block-block61) 2)
	(= (y grass_block-block61) 3)
	(= (z grass_block-block61) 3)
	(= (block-hits grass_block-block61) 0)
	(block-present grass_block-block62)
	(= (x grass_block-block62) 2)
	(= (y grass_block-block62) 3)
	(= (z grass_block-block62) 4)
	(= (block-hits grass_block-block62) 0)
	(block-present grass_block-block63)
	(= (x grass_block-block63) 3)
	(= (y grass_block-block63) 3)
	(= (z grass_block-block63) -3)
	(= (block-hits grass_block-block63) 0)
	(block-present grass_block-block64)
	(= (x grass_block-block64) 3)
	(= (y grass_block-block64) 3)
	(= (z grass_block-block64) -2)
	(= (block-hits grass_block-block64) 0)
	(block-present grass_block-block65)
	(= (x grass_block-block65) 3)
	(= (y grass_block-block65) 3)
	(= (z grass_block-block65) -1)
	(= (block-hits grass_block-block65) 0)
	(block-present grass_block-block66)
	(= (x grass_block-block66) 3)
	(= (y grass_block-block66) 3)
	(= (z grass_block-block66) 0)
	(= (block-hits grass_block-block66) 0)
	(block-present grass_block-block67)
	(= (x grass_block-block67) 3)
	(= (y grass_block-block67) 3)
	(= (z grass_block-block67) 0)
	(= (block-hits grass_block-block67) 0)
	(block-present grass_block-block68)
	(= (x grass_block-block68) 3)
	(= (y grass_block-block68) 3)
	(= (z grass_block-block68) 1)
	(= (block-hits grass_block-block68) 0)
	(block-present grass_block-block69)
	(= (x grass_block-block69) 3)
	(= (y grass_block-block69) 3)
	(= (z grass_block-block69) 2)
	(= (block-hits grass_block-block69) 0)
	(block-present grass_block-block70)
	(= (x grass_block-block70) 3)
	(= (y grass_block-block70) 3)
	(= (z grass_block-block70) 3)
	(= (block-hits grass_block-block70) 0)
	(block-present grass_block-block71)
	(= (x grass_block-block71) 3)
	(= (y grass_block-block71) 3)
	(= (z grass_block-block71) 4)
	(= (block-hits grass_block-block71) 0)
	(block-present grass_block-block72)
	(= (x grass_block-block72) 4)
	(= (y grass_block-block72) 3)
	(= (z grass_block-block72) -3)
	(= (block-hits grass_block-block72) 0)
	(block-present grass_block-block73)
	(= (x grass_block-block73) 4)
	(= (y grass_block-block73) 3)
	(= (z grass_block-block73) -2)
	(= (block-hits grass_block-block73) 0)
	(block-present grass_block-block74)
	(= (x grass_block-block74) 4)
	(= (y grass_block-block74) 3)
	(= (z grass_block-block74) -1)
	(= (block-hits grass_block-block74) 0)
	(block-present grass_block-block75)
	(= (x grass_block-block75) 4)
	(= (y grass_block-block75) 3)
	(= (z grass_block-block75) 0)
	(= (block-hits grass_block-block75) 0)
	(block-present grass_block-block76)
	(= (x grass_block-block76) 4)
	(= (y grass_block-block76) 3)
	(= (z grass_block-block76) 0)
	(= (block-hits grass_block-block76) 0)
	(block-present grass_block-block77)
	(= (x grass_block-block77) 4)
	(= (y grass_block-block77) 3)
	(= (z grass_block-block77) 1)
	(= (block-hits grass_block-block77) 0)
	(block-present grass_block-block78)
	(= (x grass_block-block78) 4)
	(= (y grass_block-block78) 3)
	(= (z grass_block-block78) 2)
	(= (block-hits grass_block-block78) 0)
	(block-present grass_block-block79)
	(= (x grass_block-block79) 4)
	(= (y grass_block-block79) 3)
	(= (z grass_block-block79) 3)
	(= (block-hits grass_block-block79) 0)
	(block-present grass_block-block80)
	(= (x grass_block-block80) 4)
	(= (y grass_block-block80) 3)
	(= (z grass_block-block80) 4)
	(= (block-hits grass_block-block80) 0)
	(block-present obsidian-block0)
	(= (x obsidian-block0) 0)
	(= (y obsidian-block0) 4)
	(= (z obsidian-block0) -3)
	(= (block-hits obsidian-block0) 0)
	(block-present log-block0)
	(= (x log-block0) 0)
	(= (y log-block0) 5)
	(= (z log-block0) 1)
	(= (block-hits log-block0) 0)
	(item-present diamond0)
	(= (x diamond0) 5)
	(= (y diamond0) 4)
	(= (z diamond0) 5)
	(not (item-present log0))
	(= (x log0) 0)
	(= (y log0) 4)
	(= (z log0) 0)
)
(:goal
	(and (goal-achieved steve)
		
))
)