(move-east steve position0 position0 position1 position5 position4)
(jumpup-east steve position0 position1 position2 position5 position6 position4)
(jumpup-east steve position0 position2 position3 position6 position7 position5)
(jumpup-east steve position0 position3 position4 position7 position8 position6)
(jumpup-east steve position0 position4 position5 position8 position9 position7)
(move-east steve position0 position5 position6 position9 position8)
(place-planks-east steve planks-block0 position6 position7 position8 position7 position0 count1 count0)
(checkgoal steve)
; cost = 8 (unit cost)
