FROM ubuntu:20.04

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata curl ca-certificates fontconfig locales vim git\
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_VERSION jdk-17

RUN apt update
RUN apt install openjdk-17-jdk openjdk-17-jre -y

ENV JAVA_HOME=/opt/java/openjdk \
    PATH="/opt/java/openjdk/bin:$PATH"

# Setup ENHSP19
COPY . /root/enhsp20/

# java -jar enhsp-dist/enhsp.jar -o <domain_file> -f <problem_file>
WORKDIR /root/enhsp20/
RUN mkdir pddl 
ENTRYPOINT ["java", "-jar","/root/enhsp20/enhsp-20.jar"]

